---
fixtures:
  forge_modules:
    concat:
      repo: "puppetlabs/concat"
      ref: "2.2.1"
    stdlib: "puppetlabs/stdlib"
    file_concat:
      repo: "electrical/file_concat"
      ref: "1.0.1"
  symlinks:
    awscli: "#{source_dir}"
